/* automatically generated by rust-bindgen 0.72.1 */

extern "C" {
    #[link_name="rust_helper_atomic_read"]
    pub fn atomic_read(v: *const atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_read_acquire"]
    pub fn atomic_read_acquire(v: *const atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_set"]
    pub fn atomic_set(v: *mut atomic_t, i: ffi::c_int);
}
extern "C" {
    #[link_name="rust_helper_atomic_set_release"]
    pub fn atomic_set_release(v: *mut atomic_t, i: ffi::c_int);
}
extern "C" {
    #[link_name="rust_helper_atomic_add"]
    pub fn atomic_add(i: ffi::c_int, v: *mut atomic_t);
}
extern "C" {
    #[link_name="rust_helper_atomic_add_return"]
    pub fn atomic_add_return(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_add_return_acquire"]
    pub fn atomic_add_return_acquire(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_add_return_release"]
    pub fn atomic_add_return_release(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_add_return_relaxed"]
    pub fn atomic_add_return_relaxed(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_add"]
    pub fn atomic_fetch_add(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_add_acquire"]
    pub fn atomic_fetch_add_acquire(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_add_release"]
    pub fn atomic_fetch_add_release(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_add_relaxed"]
    pub fn atomic_fetch_add_relaxed(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_sub"]
    pub fn atomic_sub(i: ffi::c_int, v: *mut atomic_t);
}
extern "C" {
    #[link_name="rust_helper_atomic_sub_return"]
    pub fn atomic_sub_return(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_sub_return_acquire"]
    pub fn atomic_sub_return_acquire(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_sub_return_release"]
    pub fn atomic_sub_return_release(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_sub_return_relaxed"]
    pub fn atomic_sub_return_relaxed(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_sub"]
    pub fn atomic_fetch_sub(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_sub_acquire"]
    pub fn atomic_fetch_sub_acquire(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_sub_release"]
    pub fn atomic_fetch_sub_release(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_sub_relaxed"]
    pub fn atomic_fetch_sub_relaxed(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_inc"]
    pub fn atomic_inc(v: *mut atomic_t);
}
extern "C" {
    #[link_name="rust_helper_atomic_inc_return"]
    pub fn atomic_inc_return(v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_inc_return_acquire"]
    pub fn atomic_inc_return_acquire(v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_inc_return_release"]
    pub fn atomic_inc_return_release(v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_inc_return_relaxed"]
    pub fn atomic_inc_return_relaxed(v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_inc"]
    pub fn atomic_fetch_inc(v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_inc_acquire"]
    pub fn atomic_fetch_inc_acquire(v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_inc_release"]
    pub fn atomic_fetch_inc_release(v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_inc_relaxed"]
    pub fn atomic_fetch_inc_relaxed(v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_dec"]
    pub fn atomic_dec(v: *mut atomic_t);
}
extern "C" {
    #[link_name="rust_helper_atomic_dec_return"]
    pub fn atomic_dec_return(v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_dec_return_acquire"]
    pub fn atomic_dec_return_acquire(v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_dec_return_release"]
    pub fn atomic_dec_return_release(v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_dec_return_relaxed"]
    pub fn atomic_dec_return_relaxed(v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_dec"]
    pub fn atomic_fetch_dec(v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_dec_acquire"]
    pub fn atomic_fetch_dec_acquire(v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_dec_release"]
    pub fn atomic_fetch_dec_release(v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_dec_relaxed"]
    pub fn atomic_fetch_dec_relaxed(v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_and"]
    pub fn atomic_and(i: ffi::c_int, v: *mut atomic_t);
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_and"]
    pub fn atomic_fetch_and(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_and_acquire"]
    pub fn atomic_fetch_and_acquire(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_and_release"]
    pub fn atomic_fetch_and_release(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_and_relaxed"]
    pub fn atomic_fetch_and_relaxed(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_andnot"]
    pub fn atomic_andnot(i: ffi::c_int, v: *mut atomic_t);
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_andnot"]
    pub fn atomic_fetch_andnot(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_andnot_acquire"]
    pub fn atomic_fetch_andnot_acquire(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_andnot_release"]
    pub fn atomic_fetch_andnot_release(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_andnot_relaxed"]
    pub fn atomic_fetch_andnot_relaxed(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_or"]
    pub fn atomic_or(i: ffi::c_int, v: *mut atomic_t);
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_or"]
    pub fn atomic_fetch_or(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_or_acquire"]
    pub fn atomic_fetch_or_acquire(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_or_release"]
    pub fn atomic_fetch_or_release(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_or_relaxed"]
    pub fn atomic_fetch_or_relaxed(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_xor"]
    pub fn atomic_xor(i: ffi::c_int, v: *mut atomic_t);
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_xor"]
    pub fn atomic_fetch_xor(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_xor_acquire"]
    pub fn atomic_fetch_xor_acquire(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_xor_release"]
    pub fn atomic_fetch_xor_release(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_xor_relaxed"]
    pub fn atomic_fetch_xor_relaxed(i: ffi::c_int, v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_xchg"]
    pub fn atomic_xchg(v: *mut atomic_t, new: ffi::c_int) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_xchg_acquire"]
    pub fn atomic_xchg_acquire(v: *mut atomic_t, new: ffi::c_int) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_xchg_release"]
    pub fn atomic_xchg_release(v: *mut atomic_t, new: ffi::c_int) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_xchg_relaxed"]
    pub fn atomic_xchg_relaxed(v: *mut atomic_t, new: ffi::c_int) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_cmpxchg"]
    pub fn atomic_cmpxchg(
        v: *mut atomic_t,
        old: ffi::c_int,
        new: ffi::c_int,
    ) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_cmpxchg_acquire"]
    pub fn atomic_cmpxchg_acquire(
        v: *mut atomic_t,
        old: ffi::c_int,
        new: ffi::c_int,
    ) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_cmpxchg_release"]
    pub fn atomic_cmpxchg_release(
        v: *mut atomic_t,
        old: ffi::c_int,
        new: ffi::c_int,
    ) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_cmpxchg_relaxed"]
    pub fn atomic_cmpxchg_relaxed(
        v: *mut atomic_t,
        old: ffi::c_int,
        new: ffi::c_int,
    ) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_try_cmpxchg"]
    pub fn atomic_try_cmpxchg(
        v: *mut atomic_t,
        old: *mut ffi::c_int,
        new: ffi::c_int,
    ) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic_try_cmpxchg_acquire"]
    pub fn atomic_try_cmpxchg_acquire(
        v: *mut atomic_t,
        old: *mut ffi::c_int,
        new: ffi::c_int,
    ) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic_try_cmpxchg_release"]
    pub fn atomic_try_cmpxchg_release(
        v: *mut atomic_t,
        old: *mut ffi::c_int,
        new: ffi::c_int,
    ) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic_try_cmpxchg_relaxed"]
    pub fn atomic_try_cmpxchg_relaxed(
        v: *mut atomic_t,
        old: *mut ffi::c_int,
        new: ffi::c_int,
    ) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic_sub_and_test"]
    pub fn atomic_sub_and_test(i: ffi::c_int, v: *mut atomic_t) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic_dec_and_test"]
    pub fn atomic_dec_and_test(v: *mut atomic_t) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic_inc_and_test"]
    pub fn atomic_inc_and_test(v: *mut atomic_t) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic_add_negative"]
    pub fn atomic_add_negative(i: ffi::c_int, v: *mut atomic_t) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic_add_negative_acquire"]
    pub fn atomic_add_negative_acquire(i: ffi::c_int, v: *mut atomic_t) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic_add_negative_release"]
    pub fn atomic_add_negative_release(i: ffi::c_int, v: *mut atomic_t) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic_add_negative_relaxed"]
    pub fn atomic_add_negative_relaxed(i: ffi::c_int, v: *mut atomic_t) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic_fetch_add_unless"]
    pub fn atomic_fetch_add_unless(
        v: *mut atomic_t,
        a: ffi::c_int,
        u: ffi::c_int,
    ) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic_add_unless"]
    pub fn atomic_add_unless(v: *mut atomic_t, a: ffi::c_int, u: ffi::c_int) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic_inc_not_zero"]
    pub fn atomic_inc_not_zero(v: *mut atomic_t) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic_inc_unless_negative"]
    pub fn atomic_inc_unless_negative(v: *mut atomic_t) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic_dec_unless_positive"]
    pub fn atomic_dec_unless_positive(v: *mut atomic_t) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic_dec_if_positive"]
    pub fn atomic_dec_if_positive(v: *mut atomic_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_atomic64_read"]
    pub fn atomic64_read(v: *const atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_read_acquire"]
    pub fn atomic64_read_acquire(v: *const atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_set"]
    pub fn atomic64_set(v: *mut atomic64_t, i: s64);
}
extern "C" {
    #[link_name="rust_helper_atomic64_set_release"]
    pub fn atomic64_set_release(v: *mut atomic64_t, i: s64);
}
extern "C" {
    #[link_name="rust_helper_atomic64_add"]
    pub fn atomic64_add(i: s64, v: *mut atomic64_t);
}
extern "C" {
    #[link_name="rust_helper_atomic64_add_return"]
    pub fn atomic64_add_return(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_add_return_acquire"]
    pub fn atomic64_add_return_acquire(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_add_return_release"]
    pub fn atomic64_add_return_release(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_add_return_relaxed"]
    pub fn atomic64_add_return_relaxed(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_add"]
    pub fn atomic64_fetch_add(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_add_acquire"]
    pub fn atomic64_fetch_add_acquire(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_add_release"]
    pub fn atomic64_fetch_add_release(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_add_relaxed"]
    pub fn atomic64_fetch_add_relaxed(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_sub"]
    pub fn atomic64_sub(i: s64, v: *mut atomic64_t);
}
extern "C" {
    #[link_name="rust_helper_atomic64_sub_return"]
    pub fn atomic64_sub_return(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_sub_return_acquire"]
    pub fn atomic64_sub_return_acquire(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_sub_return_release"]
    pub fn atomic64_sub_return_release(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_sub_return_relaxed"]
    pub fn atomic64_sub_return_relaxed(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_sub"]
    pub fn atomic64_fetch_sub(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_sub_acquire"]
    pub fn atomic64_fetch_sub_acquire(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_sub_release"]
    pub fn atomic64_fetch_sub_release(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_sub_relaxed"]
    pub fn atomic64_fetch_sub_relaxed(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_inc"]
    pub fn atomic64_inc(v: *mut atomic64_t);
}
extern "C" {
    #[link_name="rust_helper_atomic64_inc_return"]
    pub fn atomic64_inc_return(v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_inc_return_acquire"]
    pub fn atomic64_inc_return_acquire(v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_inc_return_release"]
    pub fn atomic64_inc_return_release(v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_inc_return_relaxed"]
    pub fn atomic64_inc_return_relaxed(v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_inc"]
    pub fn atomic64_fetch_inc(v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_inc_acquire"]
    pub fn atomic64_fetch_inc_acquire(v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_inc_release"]
    pub fn atomic64_fetch_inc_release(v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_inc_relaxed"]
    pub fn atomic64_fetch_inc_relaxed(v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_dec"]
    pub fn atomic64_dec(v: *mut atomic64_t);
}
extern "C" {
    #[link_name="rust_helper_atomic64_dec_return"]
    pub fn atomic64_dec_return(v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_dec_return_acquire"]
    pub fn atomic64_dec_return_acquire(v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_dec_return_release"]
    pub fn atomic64_dec_return_release(v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_dec_return_relaxed"]
    pub fn atomic64_dec_return_relaxed(v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_dec"]
    pub fn atomic64_fetch_dec(v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_dec_acquire"]
    pub fn atomic64_fetch_dec_acquire(v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_dec_release"]
    pub fn atomic64_fetch_dec_release(v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_dec_relaxed"]
    pub fn atomic64_fetch_dec_relaxed(v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_and"]
    pub fn atomic64_and(i: s64, v: *mut atomic64_t);
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_and"]
    pub fn atomic64_fetch_and(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_and_acquire"]
    pub fn atomic64_fetch_and_acquire(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_and_release"]
    pub fn atomic64_fetch_and_release(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_and_relaxed"]
    pub fn atomic64_fetch_and_relaxed(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_andnot"]
    pub fn atomic64_andnot(i: s64, v: *mut atomic64_t);
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_andnot"]
    pub fn atomic64_fetch_andnot(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_andnot_acquire"]
    pub fn atomic64_fetch_andnot_acquire(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_andnot_release"]
    pub fn atomic64_fetch_andnot_release(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_andnot_relaxed"]
    pub fn atomic64_fetch_andnot_relaxed(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_or"]
    pub fn atomic64_or(i: s64, v: *mut atomic64_t);
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_or"]
    pub fn atomic64_fetch_or(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_or_acquire"]
    pub fn atomic64_fetch_or_acquire(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_or_release"]
    pub fn atomic64_fetch_or_release(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_or_relaxed"]
    pub fn atomic64_fetch_or_relaxed(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_xor"]
    pub fn atomic64_xor(i: s64, v: *mut atomic64_t);
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_xor"]
    pub fn atomic64_fetch_xor(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_xor_acquire"]
    pub fn atomic64_fetch_xor_acquire(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_xor_release"]
    pub fn atomic64_fetch_xor_release(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_xor_relaxed"]
    pub fn atomic64_fetch_xor_relaxed(i: s64, v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_xchg"]
    pub fn atomic64_xchg(v: *mut atomic64_t, new: s64) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_xchg_acquire"]
    pub fn atomic64_xchg_acquire(v: *mut atomic64_t, new: s64) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_xchg_release"]
    pub fn atomic64_xchg_release(v: *mut atomic64_t, new: s64) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_xchg_relaxed"]
    pub fn atomic64_xchg_relaxed(v: *mut atomic64_t, new: s64) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_cmpxchg"]
    pub fn atomic64_cmpxchg(v: *mut atomic64_t, old: s64, new: s64) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_cmpxchg_acquire"]
    pub fn atomic64_cmpxchg_acquire(v: *mut atomic64_t, old: s64, new: s64) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_cmpxchg_release"]
    pub fn atomic64_cmpxchg_release(v: *mut atomic64_t, old: s64, new: s64) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_cmpxchg_relaxed"]
    pub fn atomic64_cmpxchg_relaxed(v: *mut atomic64_t, old: s64, new: s64) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_try_cmpxchg"]
    pub fn atomic64_try_cmpxchg(v: *mut atomic64_t, old: *mut s64, new: s64) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic64_try_cmpxchg_acquire"]
    pub fn atomic64_try_cmpxchg_acquire(
        v: *mut atomic64_t,
        old: *mut s64,
        new: s64,
    ) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic64_try_cmpxchg_release"]
    pub fn atomic64_try_cmpxchg_release(
        v: *mut atomic64_t,
        old: *mut s64,
        new: s64,
    ) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic64_try_cmpxchg_relaxed"]
    pub fn atomic64_try_cmpxchg_relaxed(
        v: *mut atomic64_t,
        old: *mut s64,
        new: s64,
    ) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic64_sub_and_test"]
    pub fn atomic64_sub_and_test(i: s64, v: *mut atomic64_t) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic64_dec_and_test"]
    pub fn atomic64_dec_and_test(v: *mut atomic64_t) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic64_inc_and_test"]
    pub fn atomic64_inc_and_test(v: *mut atomic64_t) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic64_add_negative"]
    pub fn atomic64_add_negative(i: s64, v: *mut atomic64_t) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic64_add_negative_acquire"]
    pub fn atomic64_add_negative_acquire(i: s64, v: *mut atomic64_t) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic64_add_negative_release"]
    pub fn atomic64_add_negative_release(i: s64, v: *mut atomic64_t) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic64_add_negative_relaxed"]
    pub fn atomic64_add_negative_relaxed(i: s64, v: *mut atomic64_t) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic64_fetch_add_unless"]
    pub fn atomic64_fetch_add_unless(v: *mut atomic64_t, a: s64, u: s64) -> s64;
}
extern "C" {
    #[link_name="rust_helper_atomic64_add_unless"]
    pub fn atomic64_add_unless(v: *mut atomic64_t, a: s64, u: s64) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic64_inc_not_zero"]
    pub fn atomic64_inc_not_zero(v: *mut atomic64_t) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic64_inc_unless_negative"]
    pub fn atomic64_inc_unless_negative(v: *mut atomic64_t) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic64_dec_unless_positive"]
    pub fn atomic64_dec_unless_positive(v: *mut atomic64_t) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_atomic64_dec_if_positive"]
    pub fn atomic64_dec_if_positive(v: *mut atomic64_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_auxiliary_device_uninit"]
    pub fn auxiliary_device_uninit(adev: *mut auxiliary_device);
}
extern "C" {
    #[link_name="rust_helper_auxiliary_device_delete"]
    pub fn auxiliary_device_delete(adev: *mut auxiliary_device);
}
extern "C" {
    #[link_name="rust_helper_smp_mb"]
    pub fn smp_mb();
}
extern "C" {
    #[link_name="rust_helper_smp_wmb"]
    pub fn smp_wmb();
}
extern "C" {
    #[link_name="rust_helper_smp_rmb"]
    pub fn smp_rmb();
}
extern "C" {
    #[link_name="rust_helper_list_lru_count"]
    pub fn list_lru_count(lru: *mut list_lru) -> ffi::c_ulong;
}
extern "C" {
    #[link_name="rust_helper_list_lru_walk"]
    pub fn list_lru_walk(
        lru: *mut list_lru,
        isolate: list_lru_walk_cb,
        cb_arg: *mut ffi::c_void,
        nr_to_walk: ffi::c_ulong,
    ) -> ffi::c_ulong;
}
extern "C" {
    #[link_name="rust_helper_init_task_work"]
    pub fn init_task_work(twork: *mut callback_head, func: task_work_func_t);
}
extern "C" {
    #[link_name="rust_helper_bitmap_copy_and_extend"]
    pub fn bitmap_copy_and_extend(
        to: *mut ffi::c_ulong,
        from: *const ffi::c_ulong,
        count: ffi::c_uint,
        size: ffi::c_uint,
    );
}
extern "C" {
    #[link_name="rust_helper___set_bit"]
    pub fn __set_bit(nr: ffi::c_ulong, addr: *mut ffi::c_ulong);
}
extern "C" {
    #[link_name="rust_helper___clear_bit"]
    pub fn __clear_bit(nr: ffi::c_ulong, addr: *mut ffi::c_ulong);
}
extern "C" {
    #[link_name="rust_helper_set_bit"]
    pub fn set_bit(nr: ffi::c_ulong, addr: *mut ffi::c_ulong);
}
extern "C" {
    #[link_name="rust_helper_clear_bit"]
    pub fn clear_bit(nr: ffi::c_ulong, addr: *mut ffi::c_ulong);
}
extern "C" {
    #[link_name="rust_helper_blk_mq_rq_to_pdu"]
    pub fn blk_mq_rq_to_pdu(rq: *mut request) -> *mut ffi::c_void;
}
extern "C" {
    #[link_name="rust_helper_blk_mq_rq_from_pdu"]
    pub fn blk_mq_rq_from_pdu(pdu: *mut ffi::c_void) -> *mut request;
}
extern "C" {
    #[link_name="rust_helper_BUG"]
    pub fn BUG() -> !;
}
extern "C" {
    #[link_name="rust_helper_WARN_ON"]
    pub fn WARN_ON(cond: bool_) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_errname"]
    pub fn errname(err: ffi::c_int) -> *const ffi::c_char;
}
extern "C" {
    #[link_name="rust_helper_clk_get_optional"]
    pub fn clk_get_optional(dev: *mut device, id: *const ffi::c_char) -> *mut clk;
}
extern "C" {
    #[link_name="rust_helper_clk_prepare_enable"]
    pub fn clk_prepare_enable(clk: *mut clk) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_clk_disable_unprepare"]
    pub fn clk_disable_unprepare(clk: *mut clk);
}
extern "C" {
    #[link_name="rust_helper_init_completion"]
    pub fn init_completion(x: *mut completion);
}
extern "C" {
    #[link_name="rust_helper_raw_smp_processor_id"]
    pub fn raw_smp_processor_id() -> ffi::c_uint;
}
extern "C" {
    #[link_name="rust_helper_cpufreq_register_em_with_opp"]
    pub fn cpufreq_register_em_with_opp(policy: *mut cpufreq_policy);
}
extern "C" {
    #[link_name="rust_helper_cpumask_set_cpu"]
    pub fn cpumask_set_cpu(cpu: ffi::c_uint, dstp: *mut cpumask);
}
extern "C" {
    #[link_name="rust_helper___cpumask_set_cpu"]
    pub fn __cpumask_set_cpu(cpu: ffi::c_uint, dstp: *mut cpumask);
}
extern "C" {
    #[link_name="rust_helper_cpumask_clear_cpu"]
    pub fn cpumask_clear_cpu(cpu: ffi::c_int, dstp: *mut cpumask);
}
extern "C" {
    #[link_name="rust_helper___cpumask_clear_cpu"]
    pub fn __cpumask_clear_cpu(cpu: ffi::c_int, dstp: *mut cpumask);
}
extern "C" {
    #[link_name="rust_helper_cpumask_test_cpu"]
    pub fn cpumask_test_cpu(cpu: ffi::c_int, srcp: *mut cpumask) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_cpumask_setall"]
    pub fn cpumask_setall(dstp: *mut cpumask);
}
extern "C" {
    #[link_name="rust_helper_cpumask_empty"]
    pub fn cpumask_empty(srcp: *mut cpumask) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_cpumask_full"]
    pub fn cpumask_full(srcp: *mut cpumask) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_cpumask_weight"]
    pub fn cpumask_weight(srcp: *mut cpumask) -> ffi::c_uint;
}
extern "C" {
    #[link_name="rust_helper_cpumask_copy"]
    pub fn cpumask_copy(dstp: *mut cpumask, srcp: *const cpumask);
}
extern "C" {
    #[link_name="rust_helper_alloc_cpumask_var"]
    pub fn alloc_cpumask_var(mask: *mut cpumask_var_t, flags: gfp_t) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_zalloc_cpumask_var"]
    pub fn zalloc_cpumask_var(mask: *mut cpumask_var_t, flags: gfp_t) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_get_cred"]
    pub fn get_cred(cred: *const cred) -> *const cred;
}
extern "C" {
    #[link_name="rust_helper_put_cred"]
    pub fn put_cred(cred: *const cred);
}
extern "C" {
    #[link_name="rust_helper_devm_add_action"]
    pub fn devm_add_action(
        dev: *mut device,
        action: ::core::option::Option<unsafe extern "C" fn(arg1: *mut ffi::c_void)>,
        data: *mut ffi::c_void,
    ) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_devm_add_action_or_reset"]
    pub fn devm_add_action_or_reset(
        dev: *mut device,
        action: ::core::option::Option<unsafe extern "C" fn(arg1: *mut ffi::c_void)>,
        data: *mut ffi::c_void,
    ) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_dev_get_drvdata"]
    pub fn dev_get_drvdata(dev: *const device) -> *mut ffi::c_void;
}
extern "C" {
    #[link_name="rust_helper_dev_set_drvdata"]
    pub fn dev_set_drvdata(dev: *mut device, data: *mut ffi::c_void);
}
extern "C" {
    #[link_name="rust_helper_dma_alloc_attrs"]
    pub fn dma_alloc_attrs(
        dev: *mut device,
        size: usize,
        dma_handle: *mut dma_addr_t,
        flag: gfp_t,
        attrs: ffi::c_ulong,
    ) -> *mut ffi::c_void;
}
extern "C" {
    #[link_name="rust_helper_dma_free_attrs"]
    pub fn dma_free_attrs(
        dev: *mut device,
        size: usize,
        cpu_addr: *mut ffi::c_void,
        dma_handle: dma_addr_t,
        attrs: ffi::c_ulong,
    );
}
extern "C" {
    #[link_name="rust_helper_dma_set_mask_and_coherent"]
    pub fn dma_set_mask_and_coherent(dev: *mut device, mask: u64_) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_ERR_PTR"]
    pub fn ERR_PTR(err: ffi::c_long) -> *mut ffi::c_void;
}
extern "C" {
    #[link_name="rust_helper_IS_ERR"]
    pub fn IS_ERR(ptr: *const ffi::c_void) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_PTR_ERR"]
    pub fn PTR_ERR(ptr: *const ffi::c_void) -> ffi::c_long;
}
extern "C" {
    #[link_name="rust_helper_request_irq"]
    pub fn request_irq(
        irq: ffi::c_uint,
        handler: irq_handler_t,
        flags: ffi::c_ulong,
        name: *const ffi::c_char,
        dev: *mut ffi::c_void,
    ) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_get_file"]
    pub fn get_file(f: *mut file) -> *mut file;
}
extern "C" {
    #[link_name="rust_helper_ioremap"]
    pub fn ioremap(offset: phys_addr_t, size: usize) -> *mut ffi::c_void;
}
extern "C" {
    #[link_name="rust_helper_ioremap_np"]
    pub fn ioremap_np(offset: phys_addr_t, size: usize) -> *mut ffi::c_void;
}
extern "C" {
    #[link_name="rust_helper_iounmap"]
    pub fn iounmap(addr: *mut ffi::c_void);
}
extern "C" {
    #[link_name="rust_helper_readb"]
    pub fn readb(addr: *const ffi::c_void) -> u8_;
}
extern "C" {
    #[link_name="rust_helper_readw"]
    pub fn readw(addr: *const ffi::c_void) -> u16_;
}
extern "C" {
    #[link_name="rust_helper_readl"]
    pub fn readl(addr: *const ffi::c_void) -> u32_;
}
extern "C" {
    #[link_name="rust_helper_readq"]
    pub fn readq(addr: *const ffi::c_void) -> u64_;
}
extern "C" {
    #[link_name="rust_helper_writeb"]
    pub fn writeb(value: u8_, addr: *mut ffi::c_void);
}
extern "C" {
    #[link_name="rust_helper_writew"]
    pub fn writew(value: u16_, addr: *mut ffi::c_void);
}
extern "C" {
    #[link_name="rust_helper_writel"]
    pub fn writel(value: u32_, addr: *mut ffi::c_void);
}
extern "C" {
    #[link_name="rust_helper_writeq"]
    pub fn writeq(value: u64_, addr: *mut ffi::c_void);
}
extern "C" {
    #[link_name="rust_helper_readb_relaxed"]
    pub fn readb_relaxed(addr: *const ffi::c_void) -> u8_;
}
extern "C" {
    #[link_name="rust_helper_readw_relaxed"]
    pub fn readw_relaxed(addr: *const ffi::c_void) -> u16_;
}
extern "C" {
    #[link_name="rust_helper_readl_relaxed"]
    pub fn readl_relaxed(addr: *const ffi::c_void) -> u32_;
}
extern "C" {
    #[link_name="rust_helper_readq_relaxed"]
    pub fn readq_relaxed(addr: *const ffi::c_void) -> u64_;
}
extern "C" {
    #[link_name="rust_helper_writeb_relaxed"]
    pub fn writeb_relaxed(value: u8_, addr: *mut ffi::c_void);
}
extern "C" {
    #[link_name="rust_helper_writew_relaxed"]
    pub fn writew_relaxed(value: u16_, addr: *mut ffi::c_void);
}
extern "C" {
    #[link_name="rust_helper_writel_relaxed"]
    pub fn writel_relaxed(value: u32_, addr: *mut ffi::c_void);
}
extern "C" {
    #[link_name="rust_helper_writeq_relaxed"]
    pub fn writeq_relaxed(value: u64_, addr: *mut ffi::c_void);
}
extern "C" {
    #[link_name="rust_helper_resource_size"]
    pub fn resource_size(res: *mut resource) -> resource_size_t;
}
extern "C" {
    #[link_name="rust_helper_request_mem_region"]
    pub fn request_mem_region(
        start: resource_size_t,
        n: resource_size_t,
        name: *const ffi::c_char,
    ) -> *mut resource;
}
extern "C" {
    #[link_name="rust_helper_release_mem_region"]
    pub fn release_mem_region(start: resource_size_t, n: resource_size_t);
}
extern "C" {
    #[link_name="rust_helper_request_region"]
    pub fn request_region(
        start: resource_size_t,
        n: resource_size_t,
        name: *const ffi::c_char,
    ) -> *mut resource;
}
extern "C" {
    #[link_name="rust_helper_request_muxed_region"]
    pub fn request_muxed_region(
        start: resource_size_t,
        n: resource_size_t,
        name: *const ffi::c_char,
    ) -> *mut resource;
}
extern "C" {
    #[link_name="rust_helper_release_region"]
    pub fn release_region(start: resource_size_t, n: resource_size_t);
}
extern "C" {
    #[link_name="rust_helper_kunit_get_current_test"]
    pub fn kunit_get_current_test() -> *mut kunit;
}
extern "C" {
    #[link_name="rust_helper_mt_init_flags"]
    pub fn mt_init_flags(mt: *mut maple_tree, flags: ffi::c_uint);
}
extern "C" {
    #[link_name="rust_helper_mmgrab"]
    pub fn mmgrab(mm: *mut mm_struct);
}
extern "C" {
    #[link_name="rust_helper_mmdrop"]
    pub fn mmdrop(mm: *mut mm_struct);
}
extern "C" {
    #[link_name="rust_helper_mmget"]
    pub fn mmget(mm: *mut mm_struct);
}
extern "C" {
    #[link_name="rust_helper_mmget_not_zero"]
    pub fn mmget_not_zero(mm: *mut mm_struct) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_mmap_read_lock"]
    pub fn mmap_read_lock(mm: *mut mm_struct);
}
extern "C" {
    #[link_name="rust_helper_mmap_read_trylock"]
    pub fn mmap_read_trylock(mm: *mut mm_struct) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_mmap_read_unlock"]
    pub fn mmap_read_unlock(mm: *mut mm_struct);
}
extern "C" {
    #[link_name="rust_helper_vma_lookup"]
    pub fn vma_lookup(mm: *mut mm_struct, addr: ffi::c_ulong) -> *mut vm_area_struct;
}
extern "C" {
    #[link_name="rust_helper_vma_end_read"]
    pub fn vma_end_read(vma: *mut vm_area_struct);
}
extern "C" {
    #[link_name="rust_helper_mutex_lock"]
    pub fn mutex_lock(lock: *mut mutex);
}
extern "C" {
    #[link_name="rust_helper_mutex_trylock"]
    pub fn mutex_trylock(lock: *mut mutex) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper___mutex_init"]
    pub fn __mutex_init(
        mutex: *mut mutex,
        name: *const ffi::c_char,
        key: *mut lock_class_key,
    );
}
extern "C" {
    #[link_name="rust_helper_mutex_assert_is_held"]
    pub fn mutex_assert_is_held(mutex: *mut mutex);
}
extern "C" {
    #[link_name="rust_helper_mutex_destroy"]
    pub fn mutex_destroy(lock: *mut mutex);
}
extern "C" {
    #[link_name="rust_helper_is_of_node"]
    pub fn is_of_node(fwnode: *const fwnode_handle) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_alloc_pages"]
    pub fn alloc_pages(gfp_mask: gfp_t, order: ffi::c_uint) -> *mut page;
}
extern "C" {
    #[link_name="rust_helper_kmap_local_page"]
    pub fn kmap_local_page(page: *mut page) -> *mut ffi::c_void;
}
extern "C" {
    #[link_name="rust_helper_kunmap_local"]
    pub fn kunmap_local(addr: *const ffi::c_void);
}
extern "C" {
    #[link_name="rust_helper_page_to_nid"]
    pub fn page_to_nid(page: *const page) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_pci_dev_id"]
    pub fn pci_dev_id(dev: *mut pci_dev) -> u16_;
}
extern "C" {
    #[link_name="rust_helper_pci_resource_start"]
    pub fn pci_resource_start(pdev: *mut pci_dev, bar: ffi::c_int) -> resource_size_t;
}
extern "C" {
    #[link_name="rust_helper_pci_resource_len"]
    pub fn pci_resource_len(pdev: *mut pci_dev, bar: ffi::c_int) -> resource_size_t;
}
extern "C" {
    #[link_name="rust_helper_dev_is_pci"]
    pub fn dev_is_pci(dev: *const device) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_get_pid_ns"]
    pub fn get_pid_ns(ns: *mut pid_namespace) -> *mut pid_namespace;
}
extern "C" {
    #[link_name="rust_helper_put_pid_ns"]
    pub fn put_pid_ns(ns: *mut pid_namespace);
}
extern "C" {
    #[link_name="rust_helper_task_get_pid_ns"]
    pub fn task_get_pid_ns(task: *mut task_struct) -> *mut pid_namespace;
}
extern "C" {
    #[link_name="rust_helper_dev_is_platform"]
    pub fn dev_is_platform(dev: *const device) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_poll_wait"]
    pub fn poll_wait(
        filp: *mut file,
        wait_address: *mut wait_queue_head_t,
        p: *mut poll_table,
    );
}
extern "C" {
    #[link_name="rust_helper_cpu_relax"]
    pub fn cpu_relax();
}
extern "C" {
    #[link_name="rust_helper_fwnode_handle_put"]
    pub fn fwnode_handle_put(fwnode: *mut fwnode_handle);
}
extern "C" {
    #[link_name="rust_helper_rb_link_node"]
    pub fn rb_link_node(
        node: *mut rb_node,
        parent: *mut rb_node,
        rb_link: *mut *mut rb_node,
    );
}
extern "C" {
    #[link_name="rust_helper_rcu_read_lock"]
    pub fn rcu_read_lock();
}
extern "C" {
    #[link_name="rust_helper_rcu_read_unlock"]
    pub fn rcu_read_unlock();
}
extern "C" {
    #[link_name="rust_helper_REFCOUNT_INIT"]
    pub fn REFCOUNT_INIT(n: ffi::c_int) -> refcount_t;
}
extern "C" {
    #[link_name="rust_helper_refcount_set"]
    pub fn refcount_set(r: *mut refcount_t, n: ffi::c_int);
}
extern "C" {
    #[link_name="rust_helper_refcount_inc"]
    pub fn refcount_inc(r: *mut refcount_t);
}
extern "C" {
    #[link_name="rust_helper_refcount_dec"]
    pub fn refcount_dec(r: *mut refcount_t);
}
extern "C" {
    #[link_name="rust_helper_refcount_dec_and_test"]
    pub fn refcount_dec_and_test(r: *mut refcount_t) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_sg_dma_address"]
    pub fn sg_dma_address(sg: *mut scatterlist) -> dma_addr_t;
}
extern "C" {
    #[link_name="rust_helper_sg_dma_len"]
    pub fn sg_dma_len(sg: *mut scatterlist) -> ffi::c_uint;
}
extern "C" {
    #[link_name="rust_helper_sg_next"]
    pub fn sg_next(sg: *mut scatterlist) -> *mut scatterlist;
}
extern "C" {
    #[link_name="rust_helper_dma_unmap_sgtable"]
    pub fn dma_unmap_sgtable(
        dev: *mut device,
        sgt: *mut sg_table,
        dir: dma_data_direction,
        attrs: ffi::c_ulong,
    );
}
extern "C" {
    #[link_name="rust_helper_signal_pending"]
    pub fn signal_pending(t: *mut task_struct) -> ffi::c_int;
}
extern "C" {
    #[must_use]
    #[link_name="rust_helper_krealloc_node_align"]
    pub fn krealloc_node_align(
        objp: *const ffi::c_void,
        new_size: usize,
        align: ffi::c_ulong,
        flags: gfp_t,
        node: ffi::c_int,
    ) -> *mut ffi::c_void;
}
extern "C" {
    #[must_use]
    #[link_name="rust_helper_kvrealloc_node_align"]
    pub fn kvrealloc_node_align(
        p: *const ffi::c_void,
        size: usize,
        align: ffi::c_ulong,
        flags: gfp_t,
        node: ffi::c_int,
    ) -> *mut ffi::c_void;
}
extern "C" {
    #[link_name="rust_helper___spin_lock_init"]
    pub fn __spin_lock_init(
        lock: *mut spinlock_t,
        name: *const ffi::c_char,
        key: *mut lock_class_key,
    );
}
extern "C" {
    #[link_name="rust_helper_spin_lock"]
    pub fn spin_lock(lock: *mut spinlock_t);
}
extern "C" {
    #[link_name="rust_helper_spin_unlock"]
    pub fn spin_unlock(lock: *mut spinlock_t);
}
extern "C" {
    #[link_name="rust_helper_spin_trylock"]
    pub fn spin_trylock(lock: *mut spinlock_t) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_spin_assert_is_held"]
    pub fn spin_assert_is_held(lock: *mut spinlock_t);
}
extern "C" {
    #[link_name="rust_helper_lockdep_register_key"]
    pub fn lockdep_register_key(k: *mut lock_class_key);
}
extern "C" {
    #[link_name="rust_helper_lockdep_unregister_key"]
    pub fn lockdep_unregister_key(k: *mut lock_class_key);
}
extern "C" {
    #[link_name="rust_helper_might_resched"]
    pub fn might_resched();
}
extern "C" {
    #[link_name="rust_helper_get_current"]
    pub fn get_current() -> *mut task_struct;
}
extern "C" {
    #[link_name="rust_helper_get_task_struct"]
    pub fn get_task_struct(t: *mut task_struct);
}
extern "C" {
    #[link_name="rust_helper_put_task_struct"]
    pub fn put_task_struct(t: *mut task_struct);
}
extern "C" {
    #[link_name="rust_helper_task_uid"]
    pub fn task_uid(task: *mut task_struct) -> kuid_t;
}
extern "C" {
    #[link_name="rust_helper_task_euid"]
    pub fn task_euid(task: *mut task_struct) -> kuid_t;
}
extern "C" {
    #[link_name="rust_helper_uid_eq"]
    pub fn uid_eq(left: kuid_t, right: kuid_t) -> bool_;
}
extern "C" {
    #[link_name="rust_helper_current_euid"]
    pub fn current_euid() -> kuid_t;
}
extern "C" {
    #[link_name="rust_helper_current_user_ns"]
    pub fn current_user_ns() -> *mut user_namespace;
}
extern "C" {
    #[link_name="rust_helper_task_tgid_nr_ns"]
    pub fn task_tgid_nr_ns(tsk: *mut task_struct, ns: *mut pid_namespace) -> pid_t;
}
extern "C" {
    #[link_name="rust_helper_fsleep"]
    pub fn fsleep(usecs: ffi::c_ulong);
}
extern "C" {
    #[link_name="rust_helper_ktime_get_real"]
    pub fn ktime_get_real() -> ktime_t;
}
extern "C" {
    #[link_name="rust_helper_ktime_get_boottime"]
    pub fn ktime_get_boottime() -> ktime_t;
}
extern "C" {
    #[link_name="rust_helper_ktime_get_clocktai"]
    pub fn ktime_get_clocktai() -> ktime_t;
}
extern "C" {
    #[link_name="rust_helper_ktime_to_us"]
    pub fn ktime_to_us(kt: ktime_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_ktime_to_ms"]
    pub fn ktime_to_ms(kt: ktime_t) -> s64;
}
extern "C" {
    #[link_name="rust_helper_copy_from_user"]
    pub fn copy_from_user(
        to: *mut ffi::c_void,
        from: *const ffi::c_void,
        n: ffi::c_ulong,
    ) -> ffi::c_ulong;
}
extern "C" {
    #[link_name="rust_helper_copy_to_user"]
    pub fn copy_to_user(
        to: *mut ffi::c_void,
        from: *const ffi::c_void,
        n: ffi::c_ulong,
    ) -> ffi::c_ulong;
}
extern "C" {
    #[must_use]
    #[link_name="rust_helper_vrealloc_node_align"]
    pub fn vrealloc_node_align(
        p: *const ffi::c_void,
        size: usize,
        align: ffi::c_ulong,
        flags: gfp_t,
        node: ffi::c_int,
    ) -> *mut ffi::c_void;
}
extern "C" {
    #[link_name="rust_helper_init_wait"]
    pub fn init_wait(wq_entry: *mut wait_queue_entry);
}
extern "C" {
    #[link_name="rust_helper_init_work_with_key"]
    pub fn init_work_with_key(
        work: *mut work_struct,
        func: work_func_t,
        onstack: bool_,
        name: *const ffi::c_char,
        key: *mut lock_class_key,
    );
}
extern "C" {
    #[link_name="rust_helper_xa_err"]
    pub fn xa_err(entry: *mut ffi::c_void) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_xa_init_flags"]
    pub fn xa_init_flags(xa: *mut xarray, flags: gfp_t);
}
extern "C" {
    #[link_name="rust_helper_xa_trylock"]
    pub fn xa_trylock(xa: *mut xarray) -> ffi::c_int;
}
extern "C" {
    #[link_name="rust_helper_xa_lock"]
    pub fn xa_lock(xa: *mut xarray);
}
extern "C" {
    #[link_name="rust_helper_xa_unlock"]
    pub fn xa_unlock(xa: *mut xarray);
}
